version: '3'
services:
  app:
    build: .
    volumes:
      - /usr/src/app
    ports:
      - "80:3000"
    depends_on:
      - mongodbservice
  mongodbservice:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
